### ISSUE TITLE
How to explicitly define the geometric parameters of the coil when creating a model using mag_manip?

### ISSUE THREAD

**Issue by JixiongRen** [ethz-msrl/Tesla_core_public#1]
Hello, @florianheemeyer @msrl-gh-bot 
I'm trying to use the `mag_manip` package to build an electromagnetic drive system. I noticed that you used the following code in other repositories to create an instance of the forward model for an electromagnetic actuator:
```
cal_path_mns2 = 'models/mns_3coils_triangle.yaml' 
model2 = ForwardModelMPEM()  
model2.setCalibrationFile(cal_path_mns2)  
```
I tried to write a simple configuration file for our electromagnetic drive device, as follows:
```
System_Name: Supiee
Coil_List:
  - Coil_0
  - Coil_1
  - Coil_2
  - Coil_3
  - Coil_4
  - Coil_5
  - Coil_6
  - Coil_7
Coil_0:
  Source_List:
    - Src_0
  Src_0:
    A_Coeff: ~
    B_Coeff:
      - 1.e-4
    Source_Direction:
      - -0.81644005
      - 0.
      - -0.57743021
    Source_Position:
      - 0.65315204
      - 0.
      - 0.46194417
Coil_1:
  Source_List:
    - Src_0
  Src_0:
    A_Coeff: ~
    B_Coeff:
      - 1.e-4
    Source_Direction:
      - 0.
      - -0.81644005
      - -0.57743021
    Source_Position:
      - 0.
      - 0.65315204
      - 0.46194417
Coil_2:
  Source_List:
    - Src_0
  Src_0:
    A_Coeff: ~
    B_Coeff:
      - 1.e-4
    Source_Direction:
      - 0.81644005
      - 0.
      - -0.57743021
    Source_Position:
      - -0.65315204
      - 0.
      - 0.46194417
Coil_3:
  Source_List:
    - Src_0
  Src_0:
    A_Coeff: ~
    B_Coeff:
      - 1.e-4
    Source_Direction:
      - 0.
      - 0.81644005
      - -0.57743021
    Source_Position:
      - 0.
      - -0.65315204
      - 0.46194417
Coil_4:
  Source_List:
    - Src_0
  Src_0:
    A_Coeff: ~
    B_Coeff:
      - 1.e-4
    Source_Direction:
      - -0.81644005
      - 0.
      - 0.57743021
    Source_Position:
      - 0.65315204
      - 0.
      - -0.46194417
Coil_5:
  Source_List:
    - Src_0
  Src_0:
    A_Coeff: ~
    B_Coeff:
      - 1.e-4
    Source_Direction:
      - 0.
      - -0.81644005
      - 0.57743021
    Source_Position:
      - 0.
      - 0.65315204
      - -0.46194417
Coil_6:
  Source_List:
    - Src_0
  Src_0:
    A_Coeff: ~
    B_Coeff:
      - 1.e-4
    Source_Direction:
      - 0.81644005
      - 0.0
      - 0.57743021
    Source_Position:
      - -0.65315204
      - 0.
      - -0.46194417
Coil_7:
  Source_List:
    - Src_0
  Src_0:
    A_Coeff: ~
    B_Coeff:
      - 1.e-4
    Source_Direction:
      - 0.
      - 0.81644005
      - 0.57743021
    Source_Position:
      - 0.
      - -0.65315204
      - -0.46194417
Workspace_Dimensions:
  -
    - -0.275
    - 0.275
  -
    - -0.275
    - 0.275
  -
    - -0.275
    - 0.275
```
As you can see, this is an 8-pole system. I'd like to know how to explicitly define the length, radius, and number of turns of the magnet when creating the model, as this is crucial for my modeling and simulation.

Additionally, could you write a documentation for `mag_manip` and explain how to write the `yaml` file, especially the meanings of `A_Coeff `and `B_Coeff` in it?

Thank you very much!
